# Generated by Django 5.0.1 on 2026-01-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_reasoning_effort',
            field=models.CharField(choices=[('none', 'None'), ('minimal', 'Minimal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'Extra High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='white_reasoning_effort',
            field=models.CharField(choices=[('none', 'None'), ('minimal', 'Minimal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'Extra High')], default='medium', max_length=20),
        ),
    ]
