# Generated by Django 5.0.1 on 2026-01-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_black_reasoning_effort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
